- name: 'Required Programs'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
  - openssh-server
  # - git-annex
  # - mercurial
  - pandoc
  - mongodb-clients
  - tmux
  # - silversearcher-ag
  - ranger
  - caca-utils

- name: "Git: Package Installation"
  apt: name=git state=present
- name: "Git: Configure User"
  shell: "git config --global user.email '{{ user.email }}' ; git config --global user.name '{{ user.name }}'"

- name: "Haskell"
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - ghc-haddock
    - libghc-haddock-doc

- name: 'Clojure'
  apt: name={{ item }} state=present
  sudo: true
  with_items:
  - phantomjs # Austin / Clojurescript
  - default-jdk

- name: 'Vim: Packages'
  apt: name={{ item }} state=present
  sudo: true
  with_items:
  - vim
  - cmake
  - python-dev
  - build-essential
- name: 'Vim: Plugins Directory'
  file: dest=~/.vim/bundle state=directory
- name: 'Vim: Vundle Repository'
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: "Install: Node Environment - Download NVM"
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm
- name: "Install: Node Environment - NVM Permissions"
  file: path=~/.nvm/nvm.sh mode=0755
- name: "Install: Node Environment - Install Node"
  shell: ~/.nvm/nvm.sh install {{ node.version }}
- name: "Install: Node Environment - Default Node Version"
  shell: ~/.nvm/nvm.sh default {{ node.version }}

- name: "Dot Files: .scripts"
  file: force=yes src={{ terminal_developer.files }}/scripts dest=~/.scripts state=link
- name: "Dot Files: .tmux.conf"
  file: force=yes src={{ terminal_developer.files }}/tmux.conf dest=~/.tmux.conf state=link
- name: "Dot Files: .profile"
  file: force=yes src={{ terminal_developer.files }}/profile dest=~/.profile state=link
- name: "Dot Files: .bashrc"
  file: force=yes src={{ terminal_developer.files }}/bashrc dest=~/.bashrc state=link
- name: "Dot Files: .vimrc"
  file: force=yes src={{ terminal_developer.files }}/vimrc dest=~/.vimrc state=link
- name: "Dot Files: .editorconfig"
  file: force=True src={{ terminal_developer.files }}/editorconfig dest=~/.editorconfig state=link

- name: "Shell Colors"
  git: repo=https://github.com/chriskempson/base16-shell.git dest=~/.vendor/base16-shell
